jdbc:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/boottest
  username: root
  password: 123456test!

#整合其他yml文件
spring:
  profiles:
    active: go,test
  #设置数据源
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boottest
    username: root
    password: 123456test!
  redis:
    host: localhost
    port: 6379


#Tomcat端口
server:
  port: 9090

#设置日志记录级别
logging:
  level:
    com.myspringboot: debug
    org.springframework: info

mybatis:
  #实体类别名包路径
  type-aliases-package: com.myspringboot.pojo
  #映射文件路径
#  mapper-locations: classpath:mappers/*xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
